apiVersion: v1
kind: Pod
metadata:
  name: shared-data-demo
spec:
  containers:
  - name: redistestvolumes
    image: redis:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-volume
      mountPath: /data
  - name: busyboxtestvolumes
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo 'This file is shared via emptyDir' > /shared-data/test.txt && sleep 3600"]
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-data
  volumes:
  - name: shared-volume
    emptyDir: {}
